[build]
  functions = "functions"
  command = "npm install && npm run build && npm install aws-serverless-fastify"
  
[build.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "netlify-plugin-express"
